import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Image } from "next/image";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <h1 className="pt-8 font-medium text-[32px] text-center">MH Jim©</h1>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
